Fix pre-commit errors

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -199,33 +199,33 @@ jobs:
           sarif_file: ${{ steps.scan.outputs.sarif }}
           category: build-${{ inputs.image }}
 
-      # - name: Show all image tags for debugging
-      #   run: echo "${{ steps.meta.outputs.tags }}"
+          # - name: Show all image tags for debugging
+          #   run: echo "${{ steps.meta.outputs.tags }}"
 
-      # - name: Pull and save image artifact for linux/amd64
-      #   if: ${{ (inputs.build-os == 'ubi'|| inputs.image == 'operator') && !inputs.dry_run }}
-      #   run: |
-      #     docker pull --platform=linux/amd64 localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ steps.meta.outputs.version }}
-      #     docker save localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ steps.meta.outputs.version }} -o ${{ inputs.image }}-${{ steps.meta.outputs.version }}.tar
+          # - name: Pull and save image artifact for linux/amd64
+          #   if: ${{ (inputs.build-os == 'ubi'|| inputs.image == 'operator') && !inputs.dry_run }}
+          #   run: |
+          #     docker pull --platform=linux/amd64 localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ steps.meta.outputs.version }}
+          #     docker save localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ steps.meta.outputs.version }} -o ${{ inputs.image }}-${{ steps.meta.outputs.version }}.tar
 
-      # - name: Upload all image artifacts
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: ${{ inputs.image }}-${{ steps.meta.outputs.version }}
-      #     path: ${{ inputs.image }}-${{ steps.meta.outputs.version }}.tar
+          # - name: Upload all image artifacts
+          #   uses: actions/upload-artifact@v4
+          #   with:
+          #     name: ${{ inputs.image }}-${{ steps.meta.outputs.version }}
+          #     path: ${{ inputs.image }}-${{ steps.meta.outputs.version }}.tar
 
 
-      # - name: Run preflight
-      #   env:
-      #     PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
-      #   run: preflight check container ${{ inputs.image }}:ubi > preflight-result.json
+          # - name: Run preflight
+          #   env:
+          #     PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
+          #   run: preflight check container ${{ inputs.image }}:ubi > preflight-result.json
 
-      # - name: Check preflight results
-      #   run: |
-      #     failed_count=$(jq '.results.failed | length' preflight-result.json)
-      #     if [ "$failed_count" -ne 0 ]; then
-      #     echo "Preflight checks failed: $failed_count failed checks"
-      #     echo "Results for preflight-result.json:"
-      #     jq '.results.failed' preflight-result.json
-      #     exit 1
-      #     fi
+          # - name: Check preflight results
+          #   run: |
+          #     failed_count=$(jq '.results.failed | length' preflight-result.json)
+          #     if [ "$failed_count" -ne 0 ]; then
+          #     echo "Preflight checks failed: $failed_count failed checks"
+          #     echo "Results for preflight-result.json:"
+          #     jq '.results.failed' preflight-result.json
+          #     exit 1
+          #     fi
diff --git a/.github/workflows/openshift-certification.yml b/.github/workflows/openshift-certification.yml
--- a/.github/workflows/openshift-certification.yml
+++ b/.github/workflows/openshift-certification.yml
@@ -53,27 +53,27 @@ jobs:
     - name: List files after artifact download
       run: ls -l ${{ github.workspace }}/dist
 
-    # - name: Load image into Docker
-    #   run: |
-    #     docker load -i ${{ inputs.image }}-${{ inputs.image_version }}.tar
+      # - name: Load image into Docker
+      #   run: |
+      #     docker load -i ${{ inputs.image }}-${{ inputs.image_version }}.tar
 
-    # - name: Retag image for preflight
-    #   run: |
-    #     loaded_tag="localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ inputs.image_version }}"
-    #     preflight_tag="${{ inputs.image }}:ubi"
-    #     docker tag "$loaded_tag" "$preflight_tag"
+      # - name: Retag image for preflight
+      #   run: |
+      #     loaded_tag="localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ inputs.image_version }}"
+      #     preflight_tag="${{ inputs.image }}:ubi"
+      #     docker tag "$loaded_tag" "$preflight_tag"
 
-    # - name: Run preflight
-    #   env:
-    #     PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
-    #   run: preflight check container ${{ inputs.image }}:ubi > preflight-result.json
+      # - name: Run preflight
+      #   env:
+      #     PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
+      #   run: preflight check container ${{ inputs.image }}:ubi > preflight-result.json
 
-    # - name: Check preflight results
-    #   run: |
-    #     failed_count=$(jq '.results.failed | length' preflight-result.json)
-    #     if [ "$failed_count" -ne 0 ]; then
-    #     echo "Preflight checks failed: $failed_count failed checks"
-    #     echo "Results for preflight-result.json:"
-    #     jq '.results.failed' preflight-result.json
-    #     exit 1
-    #     fi
+      # - name: Check preflight results
+      #   run: |
+      #     failed_count=$(jq '.results.failed | length' preflight-result.json)
+      #     if [ "$failed_count" -ne 0 ]; then
+      #     echo "Preflight checks failed: $failed_count failed checks"
+      #     echo "Results for preflight-result.json:"
+      #     jq '.results.failed' preflight-result.json
+      #     exit 1
+      #     fi
