Debug artifact upload and download

diff --git a/.github/workflows/openshift-certification.yml b/.github/workflows/openshift-certification.yml
--- a/.github/workflows/openshift-certification.yml
+++ b/.github/workflows/openshift-certification.yml
@@ -44,35 +44,36 @@ jobs:
         chmod +x preflight-linux-amd64
         sudo mv preflight-linux-amd64 /usr/local/bin/preflight
 
-    - name: Download image artifact
-      uses: actions/download-artifact@v4
+    - name: Download Artifacts
+      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
       with:
-        name: ${{ inputs.image }}-${{ inputs.image_version }}
+        name: dist-${{ github.run_id }}
+        path: ${{ github.workspace }}/dist
 
     - name: List files after artifact download
-      run: ls -l ${{ inputs.image }}-${{ inputs.image_version }}.tar
+      run: ls -l ${{ github.workspace }}/dist
 
-    - name: Load image into Docker
-      run: |
-        docker load -i ${{ inputs.image }}-${{ inputs.image_version }}.tar
+    # - name: Load image into Docker
+    #   run: |
+    #     docker load -i ${{ inputs.image }}-${{ inputs.image_version }}.tar
 
-    - name: Retag image for preflight
-      run: |
-        loaded_tag="localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ inputs.image_version }}"
-        preflight_tag="${{ inputs.image }}:ubi"
-        docker tag "$loaded_tag" "$preflight_tag"
+    # - name: Retag image for preflight
+    #   run: |
+    #     loaded_tag="localhost:5000/nginx-gateway-fabric/${{ inputs.image }}:${{ inputs.image_version }}"
+    #     preflight_tag="${{ inputs.image }}:ubi"
+    #     docker tag "$loaded_tag" "$preflight_tag"
 
-    - name: Run preflight
-      env:
-        PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
-      run: preflight check container ${{ inputs.image }}:ubi > preflight-result.json
+    # - name: Run preflight
+    #   env:
+    #     PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
+    #   run: preflight check container ${{ inputs.image }}:ubi > preflight-result.json
 
-    - name: Check preflight results
-      run: |
-        failed_count=$(jq '.results.failed | length' preflight-result.json)
-        if [ "$failed_count" -ne 0 ]; then
-        echo "Preflight checks failed: $failed_count failed checks"
-        echo "Results for preflight-result.json:"
-        jq '.results.failed' preflight-result.json
-        exit 1
-        fi
+    # - name: Check preflight results
+    #   run: |
+    #     failed_count=$(jq '.results.failed | length' preflight-result.json)
+    #     if [ "$failed_count" -ne 0 ]; then
+    #     echo "Preflight checks failed: $failed_count failed checks"
+    #     echo "Results for preflight-result.json:"
+    #     jq '.results.failed' preflight-result.json
+    #     exit 1
+    #     fi
